# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 97e0740916b10fc626601d444e685f8bf0434790ce1959fee93db22ebf12900e853b8ae513bbe37b52f1ed1e1da1cf1cc7f3ab73f74528536a40f8fa6ecb2322

test:
  secret_key_base: aa148be20b347ad111660f28980458a30577e6b3d2383e5b38a6f0927b2644c04c6134a7f259e941e6ba43f794329fe2b42d1ef97a3b7d0cd5fd3024ee03e28d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
